### ISSUE TITLE
Can't get homeland decomp to work

### ISSUE THREAD

**Issue by exptom** [BttrDrgn/GCN-Translations#12]
I'm trying to patch my homeland ISO and have hit a problem trying to get the decomp part to work.
When I run `make` in the decomp submodule I get this error:

```
Assembling asm/main/Dolphin/__ppc_eabi_init.s
Assembling asm/main/Dolphin/__mem.s
Assembling asm/main/Dolphin/mem_TRK.s
Assembling asm/main/Dolphin/__exception.s
Assembling asm/main/Dolphin/dolphin_trk.s
Assembling asm/main/rodata.s
Assembling asm/main/text.s
Assembling asm/main/data.s
Compiling  src/main/Dolphin/ansi_files.c
Assembling asm/main/Dolphin/ansi_fp.s
Compiling  src/main/Dolphin/arith.c
Compiling  src/main/Dolphin/buffer_io.c
Compiling  src/main/Dolphin/critical_regions.gamecube.c
Compiling  src/main/Dolphin/ctype.c
Assembling asm/main/Dolphin/direct_io.s
Assembling asm/main/Dolphin/file_io.s
Assembling asm/main/Dolphin/FILE_POS.s
Assembling asm/main/Dolphin/locale.s
Assembling asm/main/rodata_1.s
Assembling asm/main/data_2.s
Assembling asm/main/Dolphin/mbstring.s
Compiling  src/main/Dolphin/mem.c
Assembling asm/main/Dolphin/mem_funcs.s
Compiling  src/main/Dolphin/misc_io.c
Assembling asm/main/text_2.s
Compiling  src/main/Dolphin/MWTrace.c
Compiling  src/main/Dolphin/MWCriticalSection_gc.cpp
Assembling asm/main/extabindex.s
Assembling asm/main/ctors.s
Assembling asm/main/dtors.s
Assembling asm/main/sdata.s
Assembling asm/main/sbss_1.s
Assembling asm/main/sdata2_1.s
Assembling asm/main/sbss2.s
Assembling asm/main/bss.s
Linking static module build/homeland.final/main.elf
Building tool tools/elf2dol
Converting build/homeland.final/main.elf to build/homeland.final/main.dol
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-as -mgekko -I include/ -W  -o asm/start/start.o asm/start/start.s
Linking relocatable module start.plf
Building tool tools/elf2rel
Converting start.plf to start.rel
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-as -mgekko -I include/ -W  -o asm/alone/alone.o asm/alone/alone.s
Linking relocatable module alone.plf
Converting alone.plf to alone.rel
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-as -mgekko -I include/ -W  -o asm/client/client.o asm/client/client.s
Linking relocatable module client.plf
Converting client.plf to client.rel
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-as -mgekko -I include/ -W  -o asm/server/server.o asm/server/server.s
Linking relocatable module server.plf
Converting server.plf to server.rel
build/homeland.final/main.dol: OK
Traceback (most recent call last):
  File "/GCN-Translations/decomp/homeland/tools/calcprogress.py", line 81, in <module>
    dol_handle = open(DOL_PATH, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'baserom.dol'
```

The homeland rom is in the `isos` directory of the main repo - not sure how the decomp is supposed to find it?

**Comment by BttrDrgn** [comment]
Oh, yes I apologize for this. I never got to the point where it was fully integrated into being used. It is currently not needed and can be skipped. It was for future planning of using it over assembly patches but I then realized there are about 4 different binaries I'd need to decompile (alone.rel, client.rel, server.rel and boot.dol) and it has become very intensive to keep up.

I will look into removing it from this project and keep it to its own separate project only.

**Comment by exptom** [comment]
Ah! I've just been building a docker container to get it all working as all the various dependencies were becoming a bit of a nightmare!

How do I skip this bit? When I run the bass main.asm it complains that the decomp doesn't exist.

**Comment by BttrDrgn** [comment]
I can quickly remove it right now as I won't be using this going forward for this. (although I hope someone else in the future finds some use for it!)

**Comment by BttrDrgn** [comment]
Please pull latest commit and try again.

**Comment by exptom** [comment]
I still get the same error with bass (which led me to try and do the decomp originally):
```
root@3bd856dfbd8c:/GCN-Translations# bass/bass games/HomeLand/Main.asm 
"../../decomp/homeland/main.dol" doesn't exist!"../../decomp/homeland/alone.rel" doesn't exist!"../../decomp/homeland/client.rel" doesn't exist!"../../decomp/homeland/start.rel" doesn't exist!
```

**Comment by BttrDrgn** [comment]
I missed something, have no idea how it properly compiled for me as I had already removed the decomp locally. 

It was trying to include the decomp files into the newly made ISO. Please try again, I apologize once more!

**Comment by exptom** [comment]
Thanks! that has finished without error. I'll try booting it later.

Would you be interested in a PR with my `Dockerfile` (and a readme update explaining how to use it)? I'm on linux and the repo is currently quite windows centric. It's taken me quite a while  to get it working and it might help someone else :slightly_smiling_face:

**Comment by BttrDrgn** [comment]
I would definitely be interested!

**Comment by exptom** [comment]
Just booted it on my GC via swiss and it works :smiley: thanks for your help!

I'll tidy up my docker stuff and do a PR in the next few days.
