### ISSUE TITLE
Can you make Donkey Konga 3 a patch?

### ISSUE THREAD

**Issue by roythearsonist** [BttrDrgn/GCN-Translations#9]
I use linux, so I can't run the bat files, and running bat files through wine never works for me. Can you distribute it as a patch file like xdelta,bps, etc?

**Comment by BttrDrgn** [comment]
Donkey Konga 3 currently doesn't compile. However, I would recommend you just use the Linux (Ubuntu only for some reason?) version of bass and slightly modify the bat to an sh as it should be incredibly simple to convert.

Bass for linux: https://github.com/ARM9/bass/releases/download/v18/bass-ubuntu.zip

The next major update will have the proper delta patches in releases.

**Comment by roythearsonist** [comment]
I'm lazy, so I guess I'll just wait. Thanks though.

**Comment by eku** [comment]
> Donkey Konga 3 currently doesn't compile.

What does this mean?

When patching I get

```
$ ./Donkey\ Konga\ 3.sh 
error: malformed expression: ""File "fs/Resource/SongInfo.res" is bigger than Size 2132"\n" [unrecognized terminal]
games/Donkey Konga 3/Main.asm:37:1: "{MESSAGE}\n"
bass: assembly failed
```

BTW you should notice on the main page, that the hash values are from SHA1.

**Comment by BttrDrgn** [comment]
What I mean from what I said is that it doesn't compile, which is literally what you showed. I don't feel like I need to indicate that the hash is SHA1 because it's obvious.

You commented on a closed issue that is unrelated, please do not do this again including this issue.
